#!/bin/bash

# Backup all installed browser plugins
su - USER -c backup-browser-plugins > /root/browser-plugins.txt

# Backup pacman installed packages list
pacman -Qqe > /root/pkglist.txt

# Create a remote backup of the entire root filesystem using tarsnap,
# excludes the directories and files matched in /etc/tarsnap/tarsnap.conf
dt=`date +"backup-%Y-%m-%d_%H:%M"`

tarsnap -c -f $dt /
